config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

  resources :posts, only: [:index, :new, :create] do
    resources :meows, only: [:create, :destroy]
  end

end

app/models/meow.rb
class Meow < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :meows

  belongs_to :post,
    inverse_of: :meows

  validates :user, presence: true
  validates :post, presence: true
  validates :post_id, uniqueness: { scope: :user_id }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user,
    inverse_of: :posts

  has_many :meows,
    dependent: :destroy,
    inverse_of: :post

  validates :user, presence: true
  validates :image, presence: true
  validates :description, length: { maximum: 140 }

  mount_uploader :image, PostImageUploader

  def self.by_recency
    order(created_at: :desc)
  end

  def has_meow_from?(user)
    meow_from(user).present?
  end

  def meow_from(user)
    meows.find_by(user_id: user.id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts,
    dependent: :destroy,
    inverse_of: :user

  has_many :meows,
    dependent: :destroy,
    inverse_of: :user
    
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/meows_controller.rb
class MeowsController < ApplicationController
  # /posts/:post_id/meows
  def create
    # Find the Post that we're "meowing" at
    post = Post.find(params[:post_id])
    # Build a Meow by the current user for the post
    meow = current_user.meows.build(post: post)

    if meow.save
      redirect_to :back, notice: "We heard your Meow!"
    else
      redirect_to :back
    end
  end

  def destroy
    current_user.meows.destroy(params[:id])
    redirect_to :back, notice: "All evidence of your meowing has been destroyed!"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.by_recency
  end

  def new
    @post = Post.new
  end

  def create
    # Building a new Post off of the current_user will use some Rails magic to
    # set up the association between the new Post and the User for us.
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to root_path, notice: "Post created successfully."
    else
      flash.now[:notice] = "There were some errors with your Post."
      render :new
    end
  end

  protected
  def post_params
    # Notice we are not permitting the user_id to be passed in. This prevents
    # users from creating posts that belong to another user.
    params.require(:post).permit(:image, :description)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catstagram</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Catstagram</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'New Post', new_post_path %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_tag do %>
    $(function(){
      $(document).foundation();
    });
  <% end %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/posts/index.html.erb
<h1>Meow</h1>

<% @posts.each do |post| %>
  <%= image_tag post.image.url %>
  <p><%= pluralize post.meows.count, "Meow" %></p>
  <% if user_signed_in? %>
    <% if post.has_meow_from?(current_user) %>
      <%= button_to "Remove Meow", post_meow_path(post, post.meow_from(current_user)),
      method: :delete %>
    <% else %>
      <%= button_to "Meow", post_meows_path(post), method: :post %>
    <% end %>
  <% end %>
  <p><%= post.description %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :image, as: :file %>
  <%= f.input :description, as: :text %>
  <%= f.button :submit %>
<% end %>